#!/usr/bin/env python3
"""Extract a .docx into a structured content model for Figma design generation.

Standard library only -- no pip installs, no pandoc. Teammates run this on a
stock python3.

Usage:
    docx_extract.py INPUT.docx [--out content.json] [--assets DIR] [--quiet]

Writes a JSON content model (see references/content-model.md) and prints a
short human-readable outline to stdout.
"""

import argparse
import json
import os
import re
import sys
import zipfile
import xml.etree.ElementTree as ET

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
A = "http://schemas.openxmlformats.org/drawingml/2006/main"
WP = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
PKG_REL = "http://schemas.openxmlformats.org/package/2006/relationships"
VML = "urn:schemas-microsoft-com:vml"

EMU_PER_PX = 9525  # 914400 EMU per inch / 96 px per inch

# Word's autogenerated image names carry no meaning; don't pass them off as alt text.
GENERIC_ALT = re.compile(r"^(drawing|image|picture|shape|graphic|chart|diagram|"
                         r"content control)\s*\d*$", re.I)


def clean_alt(value):
    value = (value or "").strip()
    return "" if GENERIC_ALT.match(value) else value


def w(tag):
    return "{%s}%s" % (W, tag)


def val(el, attr="val"):
    return el.get(w(attr)) if el is not None else None


def is_on(el):
    """A boolean run property is on unless it carries val="0"/"false"."""
    if el is None:
        return False
    v = val(el)
    return v not in ("0", "false", "off")


class Docx:
    def __init__(self, path):
        self.path = path
        try:
            self.zf = zipfile.ZipFile(path)
        except zipfile.BadZipFile:
            raise SystemExit(
                "Error: %s is not a valid .docx (Word XML) file.\n"
                "Legacy .doc and .rtf are not supported -- open it in Word or "
                "Google Docs and 'Save as' / 'Download as' .docx." % path
            )
        self.part = self._find_main_part()
        self.base = os.path.dirname(self.part)  # usually "word"
        self.doc = ET.fromstring(self.zf.read(self.part))
        self.rels = self._read_rels()
        self.style_names = self._read_styles()
        self.num_formats = self._read_numbering()

    def _maybe(self, name):
        try:
            return ET.fromstring(self.zf.read(name))
        except KeyError:
            return None

    def _find_main_part(self):
        """The main document part is named in _rels/.rels, and is NOT always
        word/document.xml -- Google Docs exports often use word/document2.xml."""
        root = self._maybe("_rels/.rels")
        if root is not None:
            for rel in root.findall("{%s}Relationship" % PKG_REL):
                if (rel.get("Type") or "").endswith("/officeDocument"):
                    target = (rel.get("Target") or "").lstrip("/")
                    if target in self.zf.namelist():
                        return target
        for cand in self.zf.namelist():
            if re.match(r"word/document\d*\.xml$", cand):
                return cand
        raise SystemExit(
            "Error: %s contains no Word document part. It may be a .doc "
            "renamed to .docx, or a Pages/ODT file. Re-save it as .docx."
            % self.path
        )

    def _sibling(self, name):
        return os.path.join(self.base, name) if self.base else name

    def _read_rels(self):
        rels = {}
        rel_path = os.path.join(
            self.base, "_rels", os.path.basename(self.part) + ".rels")
        root = self._maybe(rel_path)
        if root is None:
            return rels
        for rel in root.findall("{%s}Relationship" % PKG_REL):
            rels[rel.get("Id")] = {
                "target": rel.get("Target"),
                "mode": rel.get("TargetMode"),
                "type": rel.get("Type"),
            }
        return rels

    def _read_styles(self):
        """styleId -> human style name, e.g. Heading1 -> 'heading 1'."""
        names = {}
        root = self._maybe(self._sibling("styles.xml"))
        if root is None:
            return names
        for st in root.findall(w("style")):
            sid = st.get(w("styleId"))
            name_el = st.find(w("name"))
            if sid and name_el is not None:
                names[sid] = (val(name_el) or "").lower()
        return names

    def _read_numbering(self):
        """numId -> {ilvl: numFmt}. Used to tell bullets from numbered lists."""
        out = {}
        root = self._maybe(self._sibling("numbering.xml"))
        if root is None:
            return out
        abstract = {}
        for an in root.findall(w("abstractNum")):
            aid = an.get(w("abstractNumId"))
            levels = {}
            for lvl in an.findall(w("lvl")):
                fmt = val(lvl.find(w("numFmt")))
                levels[lvl.get(w("ilvl"))] = fmt or "bullet"
            abstract[aid] = levels
        for num in root.findall(w("num")):
            nid = num.get(w("numId"))
            aid = val(num.find(w("abstractNumId")))
            out[nid] = abstract.get(aid, {})
        return out


# --------------------------------------------------------------------------
# paragraph-level parsing
# --------------------------------------------------------------------------

def heading_level(dx, p):
    """Return 1-6 for a heading paragraph, 0 for a title, None otherwise."""
    ppr = p.find(w("pPr"))
    if ppr is None:
        return None
    style_id = val(ppr.find(w("pStyle")))
    name = dx.style_names.get(style_id, (style_id or "").lower())
    if name in ("title",):
        return 0
    m = re.match(r"heading\s*([1-9])", name)
    if m:
        return int(m.group(1))
    m = re.match(r"heading([1-9])", (style_id or "").lower())
    if m:
        return int(m.group(1))
    # Fall back to the outline level Word stores for custom heading styles.
    ol = val(ppr.find(w("outlineLvl")))
    if ol is not None and ol.isdigit() and int(ol) < 9:
        return int(ol) + 1
    return None


def list_info(dx, p):
    """Return {'level': int, 'ordered': bool} for a list paragraph, else None."""
    ppr = p.find(w("pPr"))
    if ppr is None:
        return None
    numpr = ppr.find(w("numPr"))
    if numpr is None:
        return None
    num_id = val(numpr.find(w("numId")))
    ilvl = val(numpr.find(w("ilvl"))) or "0"
    if num_id in (None, "0"):
        return None
    fmt = dx.num_formats.get(num_id, {}).get(ilvl, "bullet")
    return {"level": int(ilvl), "ordered": fmt not in ("bullet", "none")}


def run_text(r):
    """Concatenate the text payload of a single w:r, honouring breaks/tabs."""
    parts = []
    for child in r:
        tag = child.tag
        if tag == w("t"):
            parts.append(child.text or "")
        elif tag == w("tab"):
            parts.append("\t")
        elif tag in (w("br"), w("cr")):
            parts.append("\n")
        elif tag == w("noBreakHyphen"):
            parts.append("-")
    return "".join(parts)


def parse_runs(dx, container, href=None):
    """Flatten a paragraph (or hyperlink) into styled runs."""
    runs = []
    for child in container:
        if child.tag == w("hyperlink"):
            rid = child.get("{%s}id" % R)
            target = dx.rels.get(rid, {}).get("target") if rid else None
            anchor = child.get(w("anchor"))
            runs.extend(parse_runs(dx, child, href=target or (
                "#" + anchor if anchor else None)))
        elif child.tag == w("r"):
            text = run_text(child)
            if not text:
                continue
            rpr = child.find(w("rPr"))
            runs.append({
                "text": text,
                "bold": is_on(rpr.find(w("b"))) if rpr is not None else False,
                "italic": is_on(rpr.find(w("i"))) if rpr is not None else False,
                "underline": rpr is not None and rpr.find(w("u")) is not None,
                "href": href,
            })
        elif child.tag in (w("sdt"), w("smartTag"), w("ins")):
            inner = child.find(w("sdtContent")) if child.tag == w("sdt") else child
            if inner is not None:
                runs.extend(parse_runs(dx, inner, href=href))
    return _merge_runs(runs)


def _merge_runs(runs):
    """Word splits a sentence across many runs; join adjacent identical ones."""
    merged = []
    for r in runs:
        if merged:
            prev = merged[-1]
            same = all(prev[k] == r[k] for k in ("bold", "italic", "underline", "href"))
            if same:
                prev["text"] += r["text"]
                continue
        merged.append(dict(r))
    return merged


def runs_text(runs):
    return "".join(r["text"] for r in runs).strip()


def extract_images(dx, p, assets_dir, assets, rel_prefix):
    """Pull every embedded image in a paragraph out to disk."""
    found = []
    # Walk each drawing wrapper (wp:inline / wp:anchor) so size and alt text stay
    # attached to their own image -- a paragraph can hold several.
    wrappers = p.findall(".//{%s}inline" % WP) + p.findall(".//{%s}anchor" % WP)
    seen = set()
    for wrap in wrappers:
        blip = wrap.find(".//{%s}blip" % A)
        if blip is None:
            continue
        rid = blip.get("{%s}embed" % R) or blip.get("{%s}link" % R)
        img = _save_image(dx, rid, assets_dir, assets, rel_prefix)
        if not img:
            continue
        seen.add(id(blip))
        entry = dict(img)
        extent = wrap.find("{%s}extent" % WP)
        if extent is not None:
            cx, cy = extent.get("cx"), extent.get("cy")
            if cx and cy:
                entry["widthPx"] = round(int(cx) / EMU_PER_PX)
                entry["heightPx"] = round(int(cy) / EMU_PER_PX)
        docpr = wrap.find("{%s}docPr" % WP)
        if docpr is not None:
            entry["alt"] = clean_alt(docpr.get("descr") or docpr.get("name"))
        found.append(entry)
    # Any blip outside an inline/anchor wrapper (rare, but seen in the wild).
    for blip in p.findall(".//{%s}blip" % A):
        if id(blip) in seen:
            continue
        rid = blip.get("{%s}embed" % R) or blip.get("{%s}link" % R)
        img = _save_image(dx, rid, assets_dir, assets, rel_prefix)
        if img:
            found.append(dict(img))
    # Legacy VML images (older Word, pasted screenshots).
    for shape in p.findall(".//{%s}imagedata" % VML):
        img = _save_image(dx, shape.get("{%s}id" % R), assets_dir, assets, rel_prefix)
        if img:
            entry = dict(img)
            entry["alt"] = clean_alt(shape.get(w("title")))
            found.append(entry)
    return found


def _save_image(dx, rid, assets_dir, assets, rel_prefix):
    if not rid or rid not in dx.rels:
        return None
    target = dx.rels[rid]["target"]
    if dx.rels[rid].get("mode") == "External":
        return {"asset": None, "externalUrl": target, "alt": ""}
    name = os.path.basename(target)
    member = os.path.normpath(os.path.join(dx.base, target.lstrip("/")))
    if member not in dx.zf.namelist():
        member = next((n for n in dx.zf.namelist() if n.endswith("/" + name)), None)
        if member is None:
            return None
    os.makedirs(assets_dir, exist_ok=True)
    out_path = os.path.join(assets_dir, name)
    if not os.path.exists(out_path):
        with open(out_path, "wb") as fh:
            fh.write(dx.zf.read(member))
    rel = os.path.join(rel_prefix, name) if rel_prefix else out_path
    if rel not in [a["asset"] for a in assets]:
        assets.append({"asset": rel, "bytes": os.path.getsize(out_path)})
    return {"asset": rel, "alt": ""}


# Page-spec conventions used in Atomicwork website docs, which carry their
# structure in plain text rather than in Word heading styles.
SECTION_RE = re.compile(r"^section\s*([0-9]+)\s*[:.\-]?\s*(.*)$", re.I)
PLACEHOLDER_RE = re.compile(r"^(?:<([^<>]+)>|\[([^\[\]]+)\])\s*(.*)$")
LABEL_RE = re.compile(r"^([A-Za-z][A-Za-z0-9 /&'-]{1,28})\s*:\s*(.*)$")

# Recognised labels -> the role the text plays in a section.
LABEL_ROLES = {
    "tag": "eyebrow", "eyebrow": "eyebrow", "label": "eyebrow",
    "kicker": "eyebrow", "pill": "eyebrow",
    "heading": "heading", "headline": "heading", "title": "heading",
    "h1": "heading", "h2": "heading", "section heading": "heading",
    "subheading": "subheading", "subtitle": "subheading",
    "sub-heading": "subheading", "subhead": "subheading",
    "description": "body", "desc": "body", "body": "body",
    "copy": "body", "subtext": "body", "supporting text": "body",
    "paragraph": "body", "intro": "body",
    "button": "cta", "cta": "cta", "cta text": "cta",
    "button text": "cta", "primary cta": "cta", "secondary cta": "cta",
    "link": "link", "url": "link",
    "quote": "quote", "testimonial": "quote",
    "author": "attribution", "attribution": "attribution", "name": "attribution",
    "stat": "stat", "metric": "metric", "number": "stat",
    "caption": "caption", "alt": "caption", "alt text": "caption",
    "note": "note", "notes": "note", "instruction": "note",
    "seo title": "meta", "meta description": "meta", "slug": "meta", "url slug": "meta",
}


def classify_paragraph(text):
    """Detect the page-spec conventions inside a plain paragraph.

    Returns a dict of extra fields to merge onto the block, or {}.
    """
    m = SECTION_RE.match(text)
    if m and (not m.group(2) or len(m.group(2)) < 80):
        return {"marker": "section", "sectionIndex": int(m.group(1)),
                "sectionTitle": m.group(2).strip()}
    m = PLACEHOLDER_RE.match(text)
    if m:
        out = {"marker": "placeholder",
               "placeholder": (m.group(1) or m.group(2)).strip()}
        if m.group(3).strip():
            out["placeholderNote"] = m.group(3).strip()
        return out
    m = LABEL_RE.match(text)
    if m:
        label = m.group(1).strip().lower()
        role = LABEL_ROLES.get(label)
        if role:
            return {"marker": "labelled", "label": label,
                    "role": role, "value": m.group(2).strip()}
    return {}


def parse_table(dx, tbl):
    rows = []
    for tr in tbl.findall(w("tr")):
        cells = []
        for tc in tr.findall(w("tc")):
            texts = [runs_text(parse_runs(dx, p)) for p in tc.findall(w("p"))]
            cells.append("\n".join(t for t in texts if t))
        rows.append(cells)
    header = rows[0] if rows else []
    return {"type": "table", "header": header, "rows": rows[1:], "allRows": rows}


# --------------------------------------------------------------------------
# document walk
# --------------------------------------------------------------------------

def parse_body(dx, assets_dir, rel_prefix):
    body = dx.doc.find(w("body"))
    blocks, assets = [], []
    pending_list = None

    def flush_list():
        nonlocal pending_list
        if pending_list:
            blocks.append(pending_list)
            pending_list = None

    def walk(container):
        nonlocal pending_list
        for el in container:
            if el.tag == w("sdt"):
                inner = el.find(w("sdtContent"))
                if inner is not None:
                    walk(inner)
                continue
            if el.tag == w("tbl"):
                flush_list()
                blocks.append(parse_table(dx, el))
                continue
            if el.tag != w("p"):
                continue

            images = extract_images(dx, el, assets_dir, assets, rel_prefix)
            runs = parse_runs(dx, el)
            text = runs_text(runs)
            li = list_info(dx, el)
            lvl = heading_level(dx, el)

            if li is not None and text:
                item = {"level": li["level"], "text": text, "runs": runs}
                if pending_list and pending_list["ordered"] == li["ordered"]:
                    pending_list["items"].append(item)
                else:
                    flush_list()
                    pending_list = {
                        "type": "list",
                        "ordered": li["ordered"],
                        "items": [item],
                    }
            elif lvl is not None and text:
                flush_list()
                blocks.append({
                    "type": "heading",
                    "level": max(lvl, 1),
                    "isTitle": lvl == 0,
                    "text": text,
                    "runs": runs,
                })
            elif text:
                flush_list()
                links = [{"text": r["text"], "href": r["href"]}
                         for r in runs if r["href"]]
                block = {
                    "type": "paragraph",
                    "text": text,
                    "runs": runs,
                    "allBold": bool(runs) and all(r["bold"] for r in runs),
                    "links": links,
                }
                block.update(classify_paragraph(text))
                if block.get("marker") == "section":
                    block["type"] = "section_marker"
                elif block.get("marker") == "placeholder":
                    block["type"] = "placeholder"
                blocks.append(block)

            for img in images:
                flush_list()
                blocks.append(dict(img, type="image"))

    walk(body)
    flush_list()
    return blocks, assets


def detect_structure(blocks):
    """How does this document carry its structure?

    'headings'        -- real Word heading styles (blog posts, long-form)
    'section-markers' -- 'SECTION 1:' text markers (Atomicwork page specs)
    'flat'            -- neither; one undivided run of copy
    """
    if any(b["type"] == "heading" for b in blocks):
        return "headings"
    if any(b["type"] == "section_marker" for b in blocks):
        return "section-markers"
    return "flat"


def _new_section(heading, level, index=None, kind="heading"):
    return {"heading": heading, "level": level, "index": index, "kind": kind,
            "blocks": [], "subsections": []}


def _summarise(section):
    """Roll the labelled/placeholder signals up so the plan step can read a
    section's intent without walking every block."""
    roles, placeholders = {}, []
    for b in section["blocks"]:
        if b.get("role"):
            roles.setdefault(b["role"], []).append(b.get("value") or b["text"])
        if b["type"] == "placeholder":
            placeholders.append(b["placeholder"])
    section["roles"] = roles
    section["placeholders"] = placeholders
    for sub in section["subsections"]:
        _summarise(sub)
    return section


def build_sections(blocks, structure):
    """Group the flat block list into a section tree."""
    if structure == "section-markers":
        sections, current = [], None
        for b in blocks:
            if b["type"] == "section_marker":
                current = _new_section(
                    b.get("sectionTitle") or "Section %d" % b["sectionIndex"],
                    1, b.get("sectionIndex"), "section-marker")
                sections.append(current)
                continue
            if current is None:
                current = _new_section(None, 1, 0, "preamble")
                sections.append(current)
            current["blocks"].append(b)
        # Name each section from its "Heading:" label, falling back to the
        # first real line of copy -- page specs label the first section and
        # then get lazy about the rest.
        for sec in sections:
            if sec["heading"] and not sec["heading"].startswith("Section "):
                continue
            head = next((b.get("value") for b in sec["blocks"]
                         if b.get("role") == "heading" and b.get("value")), None)
            if not head:
                head = next((b["text"] for b in sec["blocks"]
                             if b["type"] == "paragraph"
                             and not b.get("marker")), None)
                if head and len(head) > 90:
                    head = head[:87].rsplit(" ", 1)[0] + "..."
            if head:
                sec["heading"] = head
        return [_summarise(s) for s in sections]

    root = _new_section(None, 0, None, "root")
    stack = [root]
    for b in blocks:
        if b["type"] == "heading":
            node = _new_section(b["text"], b["level"], None, "heading")
            while len(stack) > 1 and stack[-1]["level"] >= b["level"]:
                stack.pop()
            stack[-1]["subsections"].append(node)
            stack.append(node)
        else:
            stack[-1]["blocks"].append(b)
    sections = root["subsections"] if root["subsections"] else [root]
    return [_summarise(s) for s in sections]


def outline(sections, depth=0, lines=None):
    lines = lines if lines is not None else []
    for s in sections:
        counts = {}
        for b in s["blocks"]:
            counts[b["type"]] = counts.get(b["type"], 0) + 1
        bits = []
        if s.get("roles"):
            bits.append("roles: " + "/".join(sorted(s["roles"])))
        if s.get("placeholders"):
            bits.append("visual: " + ", ".join(s["placeholders"]))
        if counts:
            bits.append(", ".join("%d %s" % (v, k)
                                  for k, v in sorted(counts.items())))
        tag = ("S%d" % s["index"]) if s.get("kind") == "section-marker" \
            else "H%d" % s["level"]
        lines.append("%s- %s %s%s" % (
            "  " * depth, tag, s["heading"] or "(preamble)",
            "  [%s]" % "; ".join(bits) if bits else "  [empty]"))
        outline(s["subsections"], depth + 1, lines)
    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="path to the .docx file")
    ap.add_argument("--out", default=".figma-design/content.json",
                    help="where to write the content JSON")
    ap.add_argument("--assets", default=None,
                    help="directory for extracted images "
                         "(default: <out dir>/assets)")
    ap.add_argument("--quiet", action="store_true",
                    help="suppress the stdout outline")
    args = ap.parse_args()

    if not os.path.exists(args.input):
        raise SystemExit("Error: no such file: %s" % args.input)
    if args.input.lower().endswith(".doc"):
        raise SystemExit(
            "Error: legacy .doc is not supported. Re-save as .docx.")

    out_dir = os.path.dirname(os.path.abspath(args.out))
    assets_dir = args.assets or os.path.join(out_dir, "assets")
    rel_prefix = os.path.relpath(assets_dir, out_dir)

    dx = Docx(args.input)
    blocks, assets = parse_body(dx, assets_dir, rel_prefix)
    structure = detect_structure(blocks)
    sections = build_sections(blocks, structure)

    title = next((b["text"] for b in blocks
                  if b["type"] == "heading" and b.get("isTitle")), None)
    if not title:
        title = next((b["text"] for b in blocks if b["type"] == "heading"), None)
    if not title:
        title = os.path.splitext(os.path.basename(args.input))[0]

    counts = {}
    for b in blocks:
        counts[b["type"]] = counts.get(b["type"], 0) + 1

    model = {
        "source": os.path.abspath(args.input),
        "title": title,
        "structure": structure,
        "blocks": blocks,
        "sections": sections,
        "assets": assets,
        "stats": {
            "blockCounts": counts,
            "sectionCount": len(sections),
            "wordCount": sum(len(b.get("text", "").split())
                             for b in blocks if "text" in b),
        },
    }

    os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w") as fh:
        json.dump(model, fh, indent=2, ensure_ascii=False)

    if not args.quiet:
        print("Title: %s" % title)
        print("Structure: %s" % structure)
        print("Wrote: %s  (%d blocks, %d top-level sections, %d images)" % (
            args.out, len(blocks), len(sections), len(assets)))
        print("Outline:")
        for line in outline(sections):
            print(line)
        if assets:
            print("Images extracted to %s:" % assets_dir)
            for a in assets:
                print("  - %s" % a["asset"])


if __name__ == "__main__":
    main()
